"""Aircraft category, shared by the models that calibrate a distribution per
category rather than a single one across the whole fleet (cf.
models/anomalie.py, models/directness.py) — a business jet, a touring
aircraft, or a helicopter has neither the same speeds/altitudes/climb rates
as an airliner, nor the same notion of a "direct route" (a training circuit,
a scenic flight...). Checked directly on real data before adopting this for
directness too, not assumed: median/mean route-directness ratio differs
meaningfully between jet_affaire (0.895/0.839) and petit_avion (0.851/0.761)
on the training set — pooling them would have diluted petit_avion's own
baseline with flights that don't share its profile.

Table `data/reference/aircraft_categories.csv` (typecode -> categorie),
generated by scripts/build_aircraft_categories.py — replaces the former
"OpenAP recognizes this typecode" boundary: OpenAP only recognizes around
forty typecodes for its own simulation needs, which let real, recent
airliners (A330-900, A220, CRJ-1000, 787-10, E195-E2...) fall into
"petit_avion" simply because OpenAP doesn't have their performance sheet
yet — found directly on the training dataset, not a hypothesis. OpenAP is
still used elsewhere (models/_ecart_features.resolve_typecode), but only for
its real question: "does a performance model exist to simulate this
flight?" — a different question from the aircraft's category.

A typecode absent from the table returns None ("unidentified") rather than a
guessed default classification — cf. build_aircraft_categories.py for the
detail of the three classification layers (automatic helicopter detection,
automatic avion_ligne/jet_affaire via OpenAP, everything else classified by
hand for the typecodes actually encountered).
"""

from pathlib import Path

import pandas as pd

BACKEND_DIR = Path(__file__).resolve().parent.parent
REFERENCE_DIR = BACKEND_DIR.parent / "data" / "reference"
CATEGORIES_PATH = REFERENCE_DIR / "aircraft_categories.csv"

CATEGORIES = ["avion_ligne", "jet_affaire", "petit_avion", "helicoptere"]

_table: dict[str, str] | None = None


def _get_table() -> dict[str, str]:
    global _table
    if _table is None:
        df = pd.read_csv(CATEGORIES_PATH, dtype=str)
        _table = dict(zip(df["typecode"], df["categorie"]))
    return _table


def categorize(typecode: str) -> str | None:
    """One of the four categories (CATEGORIES), or None if this typecode
    isn't in the table — the aircraft is then "unidentified": no score is
    computed for it (pipeline.py), rather than a guessed default
    classification that would compare it to the wrong population."""
    return _get_table().get(typecode.strip().upper())
